import { v } from "convex/values";
import { action, internalMutation, internalQuery } from "./_generated/server";
import { internal } from "./_generated/api";
import { Id } from "./_generated/dataModel";
import { env } from "./lib/env";
import {
  applyFollowUp,
  Intent,
  parseIntent,
  parseModelIntent,
} from "./lib/intent";
import { extractJson, reasoningProvider } from "./lib/providers";
import { PROMPT_VERSIONS } from "./lib/prompts";
import { OCCASIONS, STYLES, WORKFLOWS_HINT } from "./lib/intent-vocab";

/**
 * Shopper session and intent resolution (spec §36-§40).
 *
 * Session state is structured, not a transcript. Spec §37 is explicit:
 * "Do NOT make the LLM remember everything through conversation
 * history." A transcript means every follow-up re-reads and re-infers
 * everything already said, which is both expensive and how constraints
 * get quietly dropped between turns (§101's `constraint_loss`).
 *
 * The session key is generated by the widget per shopper. It is not an
 * identity — no account, no PII — just a handle so "make it cheaper"
 * knows what "it" was.
 */

export const getSession = internalQuery({
  args: { tenantId: v.id("tenants"), sessionKey: v.string() },
  handler: async (ctx, { tenantId, sessionKey }) => {
    return await ctx.db
      .query("shopperSessions")
      .withIndex("by_tenant_and_key", (q) =>
        q.eq("tenantId", tenantId).eq("sessionKey", sessionKey),
      )
      .unique();
  },
});

export const saveSession = internalMutation({
  args: {
    tenantId: v.id("tenants"),
    sessionKey: v.string(),
    state: v.any(),
  },
  returns: v.null(),
  handler: async (ctx, { tenantId, sessionKey, state }) => {
    const existing = await ctx.db
      .query("shopperSessions")
      .withIndex("by_tenant_and_key", (q) =>
        q.eq("tenantId", tenantId).eq("sessionKey", sessionKey),
      )
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, { state, lastSeenAt: Date.now() });
    } else {
      await ctx.db.insert("shopperSessions", {
        tenantId,
        sessionKey,
        state,
        lastSeenAt: Date.now(),
        createdAt: Date.now(),
      });
    }
    return null;
  },
});

/**
 * Resolve an utterance into an intent.
 *
 * The order matters and follows §38 and §40:
 *
 *   1. If there is a session, try a follow-up transform. "Make it
 *      cheaper" is a field update, not a new search, and treating it as
 *      one loses every constraint the shopper already gave.
 *   2. Otherwise parse deterministically.
 *   3. Escalate to a model only for what the parser could not account
 *      for, merging its answer *under* what the parser established.
 */
export const resolveIntent = action({
  args: {
    publicKey: v.string(),
    utterance: v.string(),
    sessionKey: v.optional(v.string()),
  },
  handler: async (ctx, args): Promise<{ intent: Intent; escalated: boolean } | null> => {
    const tenant = await ctx.runQuery(internal.search.resolveStorefront, {
      publicKey: args.publicKey,
    });
    if (!tenant || !tenant.active) return null;

    let previous: Intent | null = null;
    if (args.sessionKey) {
      const row = await ctx.runQuery(internal.session.getSession, {
        tenantId: tenant.tenantId,
        sessionKey: args.sessionKey,
      });
      if (row) previous = row.state as Intent;
    }

    // 1. Follow-up on an existing session.
    if (previous) {
      const transformed = applyFollowUp(previous, args.utterance);
      if (transformed) {
        await persist(ctx, tenant.tenantId, args.sessionKey, transformed);
        return { intent: transformed, escalated: false };
      }
    }

    // 2. Deterministic parse.
    const parsed = parseIntent(args.utterance);
    let intent = parsed.intent;

    // 3. Escalate only the residue.
    let escalated = false;
    if (parsed.needsReasoning) {
      const provider = reasoningProvider(env("ANTHROPIC_API_KEY"), "strong");
      try {
        const response = await provider.complete({
          system: intentSystem,
          user: intentUser(args.utterance, parsed.residue),
          promptVersion: PROMPT_VERSIONS.intentParse,
          maxOutputTokens: 500,
          json: true,
        });
        const json = extractJson(response.text);
        if (json) {
          intent = parseModelIntent(json, parsed.intent);
          escalated = true;
        }
      } catch {
        // Model unavailable. The deterministic parse still stands —
        // a partial understanding beats refusing to answer.
      }
    }

    await persist(ctx, tenant.tenantId, args.sessionKey, intent);
    return { intent, escalated };
  },
});

type PersistCtx = { runMutation: (fn: never, args: never) => Promise<unknown> };

async function persist(
  ctx: PersistCtx,
  tenantId: Id<"tenants">,
  sessionKey: string | undefined,
  intent: Intent,
): Promise<void> {
  if (!sessionKey) return;
  await ctx.runMutation(internal.session.saveSession as never, {
    tenantId,
    sessionKey: sessionKey.slice(0, 80),
    state: intent,
  } as never);
}

const intentSystem = `You turn a shopper's request into structured search
constraints for a fashion store.

Rules:
- Answer ONLY with a single JSON object. No prose, no code fences.
- Use exactly the vocabulary given. Never invent a term.
- Only state a constraint the shopper actually expressed. Do not infer a
  budget, occasion or style they did not mention.
- If a phrase expresses a preference you cannot map to the vocabulary,
  put it in stylePositive or styleNegative only if it genuinely matches
  one of the allowed style terms. Otherwise omit it.`;

function intentUser(utterance: string, residue: string[]): string {
  return `Shopper said: "${utterance}"

A deterministic parser already handled the obvious parts. It could not
account for these words: ${residue.join(", ") || "none"}

Allowed workflows: ${WORKFLOWS_HINT}
Allowed occasions: ${OCCASIONS.join(" | ")}
Allowed styles: ${STYLES.join(" | ")}

Return JSON:
{
  "workflow": <workflow>,
  "occasion": <occasion or null>,
  "formality": <0-5 or null>,
  "stylePositive": [<style terms>],
  "styleNegative": [<style terms>],
  "budget": { "amount": <number>, "currency": <ISO code or null> } | null
}`;
}

/**
 * Session expiry sweep.
 *
 * Shopper sessions are not accounts and should not persist indefinitely
 * — spec §92 asks for a stated retention period, and a session that
 * outlives the shopping trip is data held for no reason.
 */
export const purgeStaleSessions = internalMutation({
  args: { olderThan: v.number(), limit: v.optional(v.number()) },
  returns: v.number(),
  handler: async (ctx, { olderThan, limit }) => {
    const stale = await ctx.db
      .query("shopperSessions")
      .withIndex("by_last_seen", (q) => q.lt("lastSeenAt", olderThan))
      .take(limit ?? 1000);
    for (const row of stale) await ctx.db.delete(row._id);
    return stale.length;
  },
});
